
import React from 'react';
import { Product, Customer, Sale, ExchangeRateRecord, TreasuryTransaction } from './types';
import {
  LayoutDashboard,
  ShoppingCart,
  Package,
  BarChart3,
  Settings,
  Search,
  Plus,
  Trash2,
  Edit,
  Minus,
  CheckCircle2,
  AlertTriangle,
  AlertCircle,
  Sparkles,
  ShoppingBag,
  TrendingUp,
  DollarSign,
  CreditCard,
  Users,
  UserPlus,
  History,
  Wallet,
  PiggyBank,
  TrendingDown,
  LayoutGrid,
  List,
  Filter,
  ArrowUpDown,
  Cloud,
  CloudOff,
  Globe,
  Smartphone,
  QrCode,
  Rocket,
  Info,
  ExternalLink,
  Check,
  Copy,
  RefreshCw,
  X,
  Download,
  XCircle,
  Monitor,
  Lock,
  Unlock,
  MousePointer2,
  Terminal,
  Play,
  Banknote,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  ChevronLeft,
  ArrowRight,
  Calendar,
  ArrowLeft,
  Building,
  Clock,
  Share,
  Loader2,
  RotateCcw,
  Save,
  Briefcase,
  Truck,
  Landmark,
  PieChart,
  FileText,
  ArrowUp,
  ArrowDown,
  Calculator,
  Divide,
  Hash,
  Tag,
  Scale,
  // Nuevos Iconos
  Box,
  Layers,
  Ruler
} from 'lucide-react';

// Initial products for the demo with costPrice added
export const INITIAL_PRODUCTS: Product[] = [];

// Datos iniciales de clientes para que no aparezca vacío
export const INITIAL_CUSTOMERS: Customer[] = [];

// Datos iniciales de ventas para tener reportes de ejemplo
export const INITIAL_SALES: Sale[] = [];

// Helper para crear fechas pasadas
const daysAgo = (days: number) => {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.getTime();
};

// Historial de Tasas Inicial
export const INITIAL_RATE_HISTORY: ExchangeRateRecord[] = [];

// Movimientos de Tesorería Iniciales
export const INITIAL_TREASURY: TreasuryTransaction[] = [];


export const CATEGORIES = ['Todas', 'Bebidas', 'Panadería', 'Comida', 'Snacks'];

export {
  LayoutDashboard,
  ShoppingCart,
  Package,
  BarChart3,
  Settings,
  Search,
  Plus,
  Trash2,
  Edit,
  Minus,
  CheckCircle2,
  AlertTriangle,
  AlertCircle,
  Sparkles,
  ShoppingBag,
  TrendingUp,
  DollarSign,
  CreditCard,
  Users,
  UserPlus,
  History,
  Wallet,
  PiggyBank,
  TrendingDown,
  LayoutGrid,
  List,
  Filter,
  ArrowUpDown,
  Cloud,
  CloudOff,
  Globe,
  Smartphone,
  QrCode,
  Rocket,
  Info,
  ExternalLink,
  Check,
  Copy,
  RefreshCw,
  X,
  Download,
  XCircle,
  Monitor,
  Lock,
  Unlock,
  MousePointer2,
  Terminal,
  Play,
  Banknote,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  ChevronLeft,
  ArrowRight,
  Calendar,
  ArrowLeft,
  Building,
  Clock,
  Share,
  Loader2,
  RotateCcw,
  Save,
  Briefcase,
  Truck,
  Landmark,
  PieChart,
  FileText,
  ArrowUp,
  ArrowDown,
  Calculator,
  Divide,
  Hash,
  Tag,
  Scale,
  Box,
  Layers,
  Ruler
};
